import comments from "@eslint-community/eslint-plugin-eslint-comments/configs";
import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import markdown from "@eslint/markdown";
import vitest from "@vitest/eslint-plugin";
// @ts-ignore -- no types for this plugin
import drizzle from "eslint-plugin-drizzle";
import jsonc from "eslint-plugin-jsonc";
import * as regexp from "eslint-plugin-regexp";
import tseslint from "typescript-eslint";

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

/**
 * Every config block that carries JS/TS rules has to name these explicitly.
 * ESLint now lints Markdown, JSON and other languages too, and a block without
 * a `files` key applies to all of them — which crashes any rule that assumes a
 * JS source tree.
 */
const SOURCE = ["**/*.{js,jsx,mjs,cjs,ts,tsx}"];

export default tseslint.config(
  {
    // `next-env.d.ts` is generated by `next dev`/`next build`, gitignored, and
    // carries a "should not be edited" notice — so any rule it trips is one we
    // could not act on anyway.
    ignores: [".next", "coverage", "next-env.d.ts"],
  },

  /**
   * `next/core-web-vitals` brings the React and Next rules but not
   * `eslint:recommended`, so the core rules were previously unenforced. It has
   * to come before the typescript-eslint block below, which switches off the
   * core rules that TypeScript already covers (`no-undef`, `no-unused-vars`);
   * the other order re-enables them and they misfire on every .tsx file.
   */
  {
    files: SOURCE,
    extends: [js.configs.recommended],
  },

  /**
   * FlatCompat emits this without a `files` key, so it would otherwise apply to
   * Markdown and JSON as well and blow up inside eslint-plugin-react.
   */
  ...compat
    .extends("next/core-web-vitals")
    .map((config) => ({ ...config, files: SOURCE })),

  {
    files: SOURCE,
    extends: [comments.recommended, regexp.configs["flat/recommended"]],
    rules: {
      // Stylistic concerns Prettier does not cover.
      "logical-assignment-operators": [
        "error",
        "always",
        { enforceForIfStatements: true },
      ],
      "no-useless-rename": "error",
      "object-shorthand": "error",
      "operator-assignment": "error",
    },
  },

  {
    files: ["**/*.ts", "**/*.tsx"],
    plugins: {
      drizzle,
    },
    extends: [
      ...tseslint.configs.recommended,
      ...tseslint.configs.recommendedTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    rules: {
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/consistent-type-definitions": "off",
      "@typescript-eslint/consistent-type-imports": [
        "warn",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/require-await": "off",
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
      "drizzle/enforce-delete-with-where": [
        "error",
        { drizzleObjectName: ["db", "ctx.db"] },
      ],
      "drizzle/enforce-update-with-where": [
        "error",
        { drizzleObjectName: ["db", "ctx.db"] },
      ],
    },
  },

  {
    files: ["**/*.test.*", "vitest.setup.ts"],
    extends: [vitest.configs.recommended],
    settings: { vitest: { typecheck: true } },
    rules: {
      // Several suites assert through helpers such as `expectAlert`, which the
      // default `["expect"]` list reads as a test with no assertions at all.
      "vitest/expect-expect": [
        "error",
        { assertFunctionNames: ["expect", "expect*"] },
      ],
    },
  },

  {
    files: ["**/*.json"],
    ignores: ["tsconfig.json", "components.json"],
    extends: [jsonc.configs["flat/recommended-with-json"]],
  },
  {
    // These two carry comments, which strict JSON forbids.
    files: ["tsconfig.json", "components.json"],
    extends: [jsonc.configs["flat/recommended-with-jsonc"]],
  },

  {
    files: ["**/*.md"],
    extends: [markdown.configs.recommended],
    rules: {
      // https://github.com/eslint/markdown/issues/294
      "markdown/no-missing-label-refs": "off",
    },
  },
  {
    // Fenced code blocks have no tsconfig behind them.
    files: ["**/*.md/*.{js,jsx,ts,tsx}"],
    extends: [tseslint.configs.disableTypeChecked],
  },

  {
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
    languageOptions: {
      parserOptions: {
        projectService: true,
      },
    },
  },
);
