import { APP_NAME } from "@/constants/app";
import { LOGIN_CODE_TTL_MINUTES } from "@/constants/auth";

/**
 * Every reason Better Auth's `emailOTP` plugin asks for a code. Only
 * `"sign-in"` is reachable from the login page today; the rest are covered so
 * that turning on password reset or email change later produces a sane email
 * instead of one addressed to the wrong situation.
 */
export type LoginCodeEmailType =
  "sign-in" | "email-verification" | "forget-password" | "change-email";

export interface LoginCodeEmail {
  subject: string;
  html: string;
  text: string;
}

interface LoginCodeEmailInput {
  /** The one-time code, already generated by Better Auth. */
  code: string;
  type: LoginCodeEmailType;
}

interface LoginCodeCopy {
  subject: string;
  /**
   * The line directly above the code. It carries the whole reason for the
   * email — there is no heading — so each variant has to name its own
   * situation rather than lean on the subject the reader has already scrolled
   * past.
   */
  lead: string;
}

const COPY: Record<LoginCodeEmailType, LoginCodeCopy> = {
  "sign-in": {
    subject: `Your ${APP_NAME} login code`,
    lead: `Enter this code to log in to your ${APP_NAME} account:`,
  },
  "email-verification": {
    subject: `Verify your email for ${APP_NAME}`,
    lead: "Enter this code to verify your email address:",
  },
  "forget-password": {
    subject: `Reset your ${APP_NAME} password`,
    lead: "Enter this code to reset your password:",
  },
  "change-email": {
    subject: `Confirm your new email for ${APP_NAME}`,
    lead: "Enter this code to confirm your new email address:",
  },
};

const GREETING = "Hi there,";

const FINE_PRINT = `This code expires in ${LOGIN_CODE_TTL_MINUTES} minutes. If you didn't request this, you can ignore this email.`;

/**
 * Signed by the product rather than by a person. A named sender would be a
 * fiction the moment a fork changes {@link APP_NAME} and forgets this line.
 */
const SIGN_OFF = {
  valediction: "Best,",
  sender: "Euan",
} as const;

/**
 * Card width. Wide enough that the fine print stays on one line and the body
 * measure lands around 65 characters, narrow enough to survive a phone without
 * the client zooming out.
 */
const CARD_WIDTH = 600;

/*
 * The brand orange is `oklch(0.705 0.187 47.6)` (#f97315) in the app, but white
 * text on it only reaches 2.8:1. The lockup therefore uses the deeper end of
 * the same hue: #db4700 as the flat fallback (4.3:1) with a gradient that
 * bottoms out at #e9580c (3.6:1), which clears AA for the 20px bold monogram
 * wherever the gradient actually renders. Outlook drops the gradient and gets
 * the flat colour, which is the safer of the two anyway.
 */
const MARK_FALLBACK = "#db4700";
const MARK_GRADIENT = "linear-gradient(135deg, #e9580c 0%, #c73f00 100%)";

const SANS =
  "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif";
const MONO =
  "ui-monospace,SFMono-Regular,Menlo,Consolas,'Courier New',monospace";

/*
 * `border-collapse:collapse` is the reflexive email reset, and it is wrong
 * here: the collapsing border model drops padding on the table box and stops
 * `border-radius` rendering, which silently flattens both the card and the
 * code box. `separate` with zero spacing removes the same cell gutters without
 * either side effect. Padding still lives on cells rather than on tables,
 * because Outlook's Word engine ignores it on a table no matter which model is
 * in use.
 */
const RESET =
  "margin:0;mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0;";

/**
 * Mail clients are not browsers: there is no CSP, no sanitiser worth relying
 * on, and the rendering path varies wildly. Escape anything interpolated even
 * though today's inputs are a digit string and a constant — `APP_NAME` is
 * meant to be edited by a fork, and that is exactly the kind of edit nobody
 * re-audits this file for.
 */
const escapeHtml = (value: string): string => {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
};

/**
 * First character of the product name, for the monogram tile.
 *
 * Split by code point rather than by `charAt`, so a name starting with an
 * emoji or an astral-plane character yields a whole glyph instead of half a
 * surrogate pair.
 */
const brandInitial = (): string => {
  return [...APP_NAME.trim()][0] ?? "";
};

/**
 * Renders the code email.
 *
 * Pure on purpose — it takes a code and returns strings, so the wording can be
 * asserted in a unit test without a network in sight, and
 * {@link import("../send-login-code-email").sendLoginCodeEmail} stays thin
 * enough to read in one go.
 *
 * The markup is deliberately old-fashioned: nested tables, inline styles, no
 * external stylesheet, no webfont, and no remote image — the lockup is a
 * coloured table cell and live text, so it survives the image blocking that is
 * on by default in most inboxes. That is the subset Outlook, Gmail's clipper,
 * and Apple Mail all agree on, and a login code is the last email that should
 * arrive looking broken.
 */
export const renderLoginCodeEmail = ({
  code,
  type,
}: LoginCodeEmailInput): LoginCodeEmail => {
  const copy = COPY[type];
  const safeCode = escapeHtml(code);
  const safeAppName = escapeHtml(APP_NAME);
  const safeInitial = escapeHtml(brandInitial());

  /*
   * `letter-spacing` on the last character pushes the digits visually
   * off-centre, so the block is nudged back by half a step. Fussy, but the
   * code is the entire point of the email.
   */
  const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!--
      Apple Mail and Outlook.com will otherwise invert this card themselves,
      and their inversion turns the muted greys into unreadable near-blacks on
      near-black. Opting out is the only way to keep a login code legible.
    -->
    <meta name="color-scheme" content="light">
    <meta name="supported-color-schemes" content="light">
    <style>
      :root { color-scheme: light; supported-color-schemes: light; }

      /*
       * Progressive enhancement: the clients that honour a head stylesheet
       * (Gmail's apps, Apple Mail, most webmail) get room back on a narrow
       * screen. Anything that strips this keeps the desktop padding, which is
       * merely snug rather than broken.
       */
      @media only screen and (max-width: 480px) {
        .card-pad { padding: 28px 20px !important; }
        .code-cell { font-size: 28px !important; letter-spacing: 8px !important; text-indent: 8px !important; }
      }
    </style>
  </head>
  <body style="margin:0;padding:0;width:100%;background-color:#f4f4f5;font-family:${SANS};-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;">
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all;">${safeCode} — ${escapeHtml(FINE_PRINT)}</div>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="${RESET}background-color:#f4f4f5;">
      <tr>
        <td align="center" style="padding:40px 16px;">
          <!--[if mso]><table role="presentation" width="${CARD_WIDTH}" cellpadding="0" cellspacing="0" border="0" align="center"><tr><td><![endif]-->
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="${RESET}max-width:${CARD_WIDTH}px;background-color:#ffffff;border-radius:12px;">
            <tr>
              <td class="card-pad" style="padding:40px 32px;">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="${RESET}">
                  <tr>
                    <td align="center" style="padding-bottom:32px;">
                      <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" style="${RESET}">
                        <tr>
                          <td width="36" height="36" align="center" valign="middle" aria-hidden="true" style="width:36px;height:36px;background-color:${MARK_FALLBACK};background-image:${MARK_GRADIENT};border-radius:9px;font-family:${SANS};font-size:20px;line-height:36px;font-weight:700;color:#ffffff;text-align:center;mso-line-height-rule:exactly;">${safeInitial}</td>
                          <td valign="middle" style="padding-left:10px;font-family:${SANS};font-size:19px;line-height:36px;font-weight:700;letter-spacing:-0.01em;color:#18181b;mso-line-height-rule:exactly;">${safeAppName}</td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td style="font-size:15px;line-height:24px;color:#18181b;padding-bottom:16px;">${escapeHtml(GREETING)}</td>
                  </tr>
                  <tr>
                    <td style="font-size:15px;line-height:24px;color:#3f3f46;padding-bottom:20px;">${escapeHtml(copy.lead)}</td>
                  </tr>
                  <tr>
                    <td style="padding-bottom:16px;">
                      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="${RESET}background-color:#fafafa;border:1px solid #e4e4e7;border-radius:8px;">
                        <tr>
                          <td align="center" class="code-cell" style="padding:22px 16px;font-family:${MONO};font-size:32px;line-height:40px;font-weight:700;letter-spacing:12px;text-indent:12px;color:#18181b;mso-line-height-rule:exactly;">${safeCode}</td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td style="font-size:13px;line-height:20px;color:#71717a;padding-bottom:28px;">${escapeHtml(FINE_PRINT)}</td>
                  </tr>
                  <tr>
                    <td style="font-size:15px;line-height:24px;color:#3f3f46;">${escapeHtml(SIGN_OFF.valediction)}<br>${escapeHtml(SIGN_OFF.sender)}</td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
          <!--[if mso]></td></tr></table><![endif]-->
        </td>
      </tr>
    </table>
  </body>
</html>`;

  /*
   * Not a fallback nobody reads: plain text is what a screen reader, a watch,
   * and a spam filter all look at first, and an email with no text part is
   * scored worse for it.
   */
  const text = [
    GREETING,
    "",
    copy.lead,
    "",
    code,
    "",
    FINE_PRINT,
    "",
    SIGN_OFF.valediction,
    SIGN_OFF.sender,
  ].join("\n");

  return { subject: copy.subject, html, text };
};
