import { describe, expect, it } from "vitest";

import { APP_NAME } from "@/constants/app";
import { LOGIN_CODE_TTL_MINUTES } from "@/constants/auth";

import {
  renderLoginCodeEmail,
  type LoginCodeEmailType,
} from "./login-code-email";

const CODE = "4821";

const render = (type: LoginCodeEmailType = "sign-in") =>
  renderLoginCodeEmail({ code: CODE, type });

describe("renderLoginCodeEmail", () => {
  it("should put the code in both the HTML and the plain text part", () => {
    const { html, text } = render();

    expect(html).toContain(CODE);
    expect(text).toContain(CODE);
  });

  it("should always produce a plain text part, since spam filters and screen readers read it first", () => {
    const { text } = render();

    expect(text.trim().length).toBeGreaterThan(0);
  });

  it("should name the product in the sign-in subject so the email is recognisable in a crowded inbox", () => {
    expect(render("sign-in").subject).toContain(APP_NAME);
  });

  it("should tell the reader how long the code lasts", () => {
    const { html, text } = render();
    const expiry = `${LOGIN_CODE_TTL_MINUTES} minutes`;

    expect(html).toContain(expiry);
    expect(text).toContain(expiry);
  });

  it("should tell an unexpecting recipient that ignoring the email is safe", () => {
    expect(render().text).toMatch(/ignore this email/i);
  });

  it.each([
    ["sign-in", /log in/i],
    ["email-verification", /verify your email/i],
    ["forget-password", /reset your password/i],
    ["change-email", /confirm your new email/i],
  ] as const)(
    "should address the %s reason rather than reusing the login wording",
    (type, heading) => {
      expect(render(type).text).toMatch(heading);
    },
  );

  it("should give every reason its own subject, so two codes are never confusable", () => {
    const types: LoginCodeEmailType[] = [
      "sign-in",
      "email-verification",
      "forget-password",
      "change-email",
    ];

    const subjects = types.map((type) => render(type).subject);

    expect(new Set(subjects).size).toBe(types.length);
  });

  /*
   * Mail clients have no CSP to fall back on. The code is generated by Better
   * Auth and is always digits today, but this asserts the escaping actually
   * runs rather than that the current input happens to be harmless.
   */
  it("should escape interpolated values instead of emitting them as markup", () => {
    const { html } = renderLoginCodeEmail({
      code: '<script>alert("x")</script>',
      type: "sign-in",
    });

    expect(html).not.toContain("<script>");
    expect(html).toContain("&lt;script&gt;");
  });

  it("should hide the preheader from the rendered body while keeping it in the source", () => {
    const { html } = render();

    // Inbox list previews read the first text in the document; without this
    // block Gmail shows a fragment of the greeting instead of the code.
    expect(html).toMatch(/display:none[^"]*opacity:0/);
  });

  it("should open with a greeting, since the email has no heading to lead with", () => {
    expect(render().text.startsWith("Hi there,")).toBe(true);
  });

  it("should sign off as Euan", () => {
    const { html, text } = render();
    const signature = "Euan";

    expect(html).toContain(signature);
    expect(text).toContain(signature);
  });

  /*
   * Most inboxes block remote images by default, so a lockup built from an
   * <img> is a blank gap exactly where the recipient looks to decide whether
   * the email is genuine. The mark is a coloured table cell and the wordmark
   * is live text for that reason.
   */
  it("should build the brand lockup from text and CSS rather than a remote image", () => {
    const { html } = render();

    expect(html).not.toMatch(/<img\b/i);
    expect(html).toContain(APP_NAME);
  });

  /*
   * Apple Mail and Outlook.com invert light emails on their own, which turns
   * the muted greys here into near-black on near-black.
   */
  it("should opt out of client-side dark mode inversion", () => {
    expect(render().html).toContain('name="color-scheme" content="light"');
  });
});
